[Variables]
; Settings
showTempTitle=1
showCoreTemps=2
showCpuTempGraph=1
showGpuTemps=1
showGpuTempGraph=1
showWaterTemps=1
showWaterTempGraph=1

fanMaxSpeed=1700

; ===== HWiNFO =====

; 
; Water Temperature
; 
; Water Temperature [HWiNFO-AquacomputerQuadro-WaterTemperature]
HWiNFO-WaterTemperature-SensorId=0xf00aa600
HWiNFO-WaterTemperature-SensorInstance=0x0
HWiNFO-WaterTemperature-EntryId=0x1000000
; Fan Speed [HWiNFO-AquacomputerQuadro-FanSpeed]
HWiNFO-FanSpeed-SensorId=0xf00aa600
HWiNFO-FanSpeed-SensorInstance=0x0
HWiNFO-FanSpeed-EntryId=0x3000001